import { readFile } from "node:fs/promises";
import { build } from "esbuild";
import { buildModularRelease } from "./lib/modular-release.mjs";

const { version } = JSON.parse(await readFile("package.json", "utf8"));

await build({
  entryPoints: ["src/index.ts"],
  outfile: "dist/gigachat-plugin.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  minify: false,
  charset: "utf8",
  // Bundled CommonJS dependencies use require() for Node built-in modules.
  banner: {
    js: `/**
 * OpenCode GigaChat plugin v${version} — standalone installation file.
 * Generated by npm run build:release. Includes third-party dependencies.
 * For readable modules, use gigachat-plugin.zip from the same release.
 * Source: https://github.com/Overman775/opencode-gigachat-plugin
 */
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);`,
  },
  logLevel: "info",
});

await buildModularRelease(version);
