import { appendFile, readFile, rm } from "node:fs/promises";
import { isBuiltin } from "node:module";
import { build } from "esbuild";
import { bundledLicenses } from "./lib/bundled-licenses.mjs";

const { version } = JSON.parse(await readFile("package.json", "utf8"));

// Remove artifacts from the former ZIP build so local outputs match the release.
await rm("dist/gigachat-plugin.zip", { force: true });
await rm("dist/release", { recursive: true, force: true });

const result = await build({
  entryPoints: ["src/index.ts"],
  outfile: "dist/gigachat-plugin.js",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  minify: false,
  charset: "utf8",
  metafile: true,
  plugins: [
    {
      name: "optional-debug-color-fallback",
      setup(builder) {
        // debug uses this optional package only to extend its color palette.
        // Preserve its default palette without resolving a user's npm package.
        builder.onResolve({ filter: /^supports-color$/ }, () => ({
          path: "supports-color",
          namespace: "optional-color",
        }));
        builder.onLoad({ filter: /.*/, namespace: "optional-color" }, () => ({
          contents: "module.exports = false;",
          loader: "js",
        }));
      },
    },
  ],
  // Bundled CommonJS dependencies use require() for Node built-in modules.
  banner: {
    js: `/**
 * OpenCode GigaChat plugin v${version} — standalone installation file.
 * Generated by npm run build:release. Includes third-party dependencies.
 * Copy this file to ~/.config/opencode/plugins/gigachat-plugin.js.
 * Source: https://github.com/Overman775/opencode-gigachat-plugin
 */
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);`,
  },
  logLevel: "info",
});

for (const output of Object.values(result.metafile.outputs)) {
  for (const dependency of output.imports) {
    if (dependency.external && !isBuiltin(dependency.path)) {
      throw new Error(`Unbundled runtime dependency: ${dependency.path}`);
    }
  }
}

const projectLicense = await readFile("LICENSE", "utf8");
const licenses = await bundledLicenses(Object.keys(result.metafile.inputs));
const notices = `Project license\n${projectLicense}\nThird-party licenses\n${licenses}`;
await appendFile(
  "dist/gigachat-plugin.js",
  `\n/*\n${notices.replaceAll("*/", "* /")}\n*/\n`,
);
